### ISSUE TITLE
Subtitles Not Working on Some Sites

### ISSUE THREAD

**Issue by KentMarlboro** [amarcu5/PiPer#69]
I haven't tried all the supported sites, but for me subtitles don't show up in the PiP window for Netflix, YouTube, and VRV.

Prime Video, Plex are the only two that work (that I've tried).

**Comment by NathanBlais** [comment]
Amazon Prime Video subtitles are also not working for me.

**Comment by amarcu5** [comment]
Thanks for the bug. For all the sites except VRV, I believe this is the same as issue #41. This is now fixed on the develop branch 653433d0e29c751672af8476d237ae257be0b60f with an expected release sometime next week.

VRV support unfortunately requires a bit more work and not sure it will make it into the next release.

**Comment by skoruppa** [comment]
@amarcu5 tried dev build on chrome from 3 days ago and the issue is still here, at least for Netflix and Youtube videos with subtitles
